name: 'health_insurance_dbt'
version: '1.0.0'
config-version: 2

profile: 'health_insurance'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  health_insurance_dbt:
    # Staging models
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate models
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      
    # Core models (dims and facts)
    core:
      +materialized: table
      +schema: core
      
    # Marts
    marts:
      +materialized: table
      +schema: marts

# Optional: Set global variables
vars:
  max_parse_error_rate: 5  # For parse_error_rate test